### DISCUSSION TITLE
Duplicated mapping key

### DISCUSSION THREAD

**Discussion by exostin** [lowlighter/metrics#1054] [Q&A] [answered]
## Expected Behavior

Code for github actions workflow works correctly when using "Repositories" plugin
## Current Behavior

Currently, on the stable branch, when using "Repositories" plugin, "Action code" tab on https://metrics.lecoq.io/ generates a code that tries to set two values to one key by default.

```
plugin_repositories: 100
plugin_repositories: yes
```
which results in an error message
```The workflow is not valid. .github/workflows/main.yml (Line: x, Col: y): 'plugin_repositories' is already defined```
x, y - depends on your workflow code
## Possible Solution

The issue can be fixed by removing one of the lines I mentioned earlier.

## Context (Environment)
I used https://metrics.lecoq.io/ to generate an action for my GitHub Readme, this was the result:

```
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: exostin
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Warsaw
          plugin_base_indepth: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: ShaderLab, HLSL
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_skipped: exostin.github.io
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_repositories: 100
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_repositories_featured: exostin/ExpiryDate, exostin/UnityBattleships
          repositories: 100
          repositories_batch: 100
```
