### DISCUSSION TITLE
How can I change the file name created by github action?

### DISCUSSION THREAD

**Discussion by Saul-Mirone** [lowlighter/metrics#1061] [Q&A] [answered]
I want to seperate the svgs generated by metrics so I can reuse them in the readme files of some repositories.

**Comment by spenserblack** [comment, marked as answer]
[The `filename` option](https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#%EF%B8%8F-available-options) should be what you need.
Example:
```yaml
- uses: lowlighter/metrics@main
  with:
    filename: custom-output.*
```
