### DISCUSSION TITLE
Api return 404

### DISCUSSION THREAD

**Discussion by tiandankanfeng** [lowlighter/metrics#1075] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/58939282/170220388-2f98a98e-25ab-474e-bf5a-d198ed4b6a5c.png)
When i use the social plugin of "Anilist watch list and reading list anilist", it happens some error which i do not know how to solve it if Anilist use no token, however others plugin works well.
The followings are my workfolw code:
```
      - name: Favorites characters  
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
```
I have created a new account in Anilist, how this plugin make a relation with the new Account?
![image](https://user-images.githubusercontent.com/58939282/170221760-713b94be-57fd-44f1-9f18-ca6b2bcc67ee.png)
