### DISCUSSION TITLE
Issues when generating Insights through Github actions

### DISCUSSION THREAD

**Discussion by pacholoamit** [lowlighter/metrics#1091] [Q&A] [answered]
Hello everyone!

I'm getting these error logs when trying to generate Insights via Github actions. For additional context, It takes up until 15 minutes when the Github workflow runs then it fails. The error message I get is `Cannot read properties of undefined (reading 'length')`. Please see the image below for more information

Here's what I have in my workflow

```yml
name: Lowlighter Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Render Insights
        uses: lowlighter/metrics@latest
        with:
          config_output: insights
          config_timezone: Asia/Manila
          token: ${{ secrets.GH_TOKEN }}
```
These are the error logs, maybe there's some documentation I missed? Thanks!

![image](https://user-images.githubusercontent.com/69985528/173244082-6eadce59-c222-43d6-99be-fb45d8feb3a3.png)
