### DISCUSSION TITLE
How to get accurate metrics

### DISCUSSION THREAD

**Discussion by CHN-ChenYi** [lowlighter/metrics#1102] [Q&A] [answered]
I encounter two weird things in my [profile repo](https://github.com/CHN-ChenYi/CHN-ChenYi).
The first one is that when I turn on the `plugin_languages_indepth` mode, it only counts about 40% of all of my commits. 
The second one is in the achievement section. I get the Master Inspirer achievement when it says that I only have a repo with 34 stars in the Maintainer badge. However, the repo helps me get the Master Inspirer has 27.1K stars. It's a repo that belongs to one of my organizations.
I don't know how to solve these two issues.

I give `gist, read:discussion, read:enterprise, read:gpg_key, read:org, read:packages, read:public_key, read:repo_hook, repo, user` scopes to the personal access token. I've also turned on `Include private contributions on my profile` in the GitHub Settings.
And the configuration file is shown below:
``` yml
name: Metrics
on:
  schedule: [{cron: "0 3,15 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: CHN-ChenYi
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Asia/Shanghai
          repositories: 200
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: true
          commits_authoring: chenyi2000@zju.edu.cn, godwings@outlook.com
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github, renderscript:#dea584
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_ignored: tcl, vhdl, coq
          plugin_languages_aliases: renderscript:Rust
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 180
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
```

Edit: I double-checked the `commits_authoring` and I'm sure that all of my private Cuda codes signed by those email addresses are not counted.
