### DISCUSSION TITLE
Beta Github Projects not showing up in Plugin Project

### DISCUSSION THREAD

**Discussion by KingNexu** [lowlighter/metrics#1134] [Q&A]
Do I have to change the setup, or is this still not supported?

**Comment by lowlighter** [comment]
Hi !

Not yet supported, but support could be added

**Reply by KingNexu** [reply]
How smart would it be to change it now, as the Projects are still in Beta?

**Reply by lowlighter** [reply]
We can support both versions while GitHub still support both

And while the new projects are still in beta, supporting at least common features is safe I guess 

I didn't check yet what exactly is different from the classic projects so I can't tell how much work/maintenance it would implies yet

**Reply by lowlighter** [reply]
There's a pretty basic support for beta projects right now on the master branch, but from what I've seen, should be doable to add other features like assignee, labels, milestones etc. 

Not sure if there is a progress tracking on new projects though

**Comment by Gregor7008** [comment]
Idk how these discussions work yet, so I'll write this here:
I got the same problem, but I have the "Licenses" field appended and it's showing me the "Unexpected error" message as well. I guess this is because on "Active projects" the rendering engine failed and then didnt restart for "Licenses", correct?
If so: Perfect, just have to wait for an update for Projects V", if not... Well I have to get to it again...

This is how it looks btw.
![image](https://user-images.githubusercontent.com/74135136/182838389-16b10ae5-1661-480c-b55d-2d5a3214e647.png)

Edit: Creation of an official issue on this planned?

**Reply by lowlighter** [reply]
Yes support for beta projects will be planned, it'll be tracked in #1175 👍 

As for your current error, is it on the web instance or GitHub Actions ? If the later, you should be able to see what the error are by checking the workflows log (there will be a small arrow to expand logs)

If possible could you also post the input parameters you passed, may also be helpful to reproduce 😄

**Reply by Gregor7008** [reply]
It is the final rendered image. And in GitHub Actions it says, that it couldn't find the project if I remember correctly. But anyways, it should be the exact same as the one @KingNexu reported. Was just wondering where the second missing component came from, as there was no error message for it - So I thought it would be a follow up error. If I'd put the projects_repositories plugin right at the beginning it'd probably skip all the image rendering and show an error for all of them, I suppose. As said: Crashed once, not restarted = Done.

But for good measure, this is my .yml file:
```
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  repository-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          repo: Butler-George
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: users/Gregor7008/projects/2
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_licenses_legal: no
          plugin_licenses_ratio: yes
```
