### DISCUSSION TITLE
Failed to show WakaTime Projects, help!!

### DISCUSSION THREAD

**Discussion by GermanBartoli** [lowlighter/metrics#1172] [Q&A]
this works correctly

```
# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: bartoligerman497
          config_timezone: America/Buenos_Aires
          template: classic
          committer_message: "chore: update metrics"

          # Stats
          # base: ""
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_octicon: yes
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: Rich Text Format
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%d

          # Waka
          plugin_wakatime: yes
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: bartoligerman497
          plugin_wakatime_days: 7
          plugin_wakatime_languages_other: yes
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          # plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
```

![image](https://user-images.githubusercontent.com/53313625/182482833-7dbdaf97-dcaa-4d77-a61d-d2cb21a8cccf.png)

does not show project activity

but if I add the token it doesn't work and it breaks (I pass the token as a secret with github secrets)

```
         plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
```

![image](https://user-images.githubusercontent.com/53313625/182482401-c981d56f-3181-4da6-870d-da16a7e42c9a.png)

help, what's wrong? 

this happened today

![image](https://user-images.githubusercontent.com/53313625/183104898-e3b4cabf-c76e-4ae7-82e0-d6b96c7c5f24.png)
