### DISCUSSION TITLE
New options for repository plugin

### DISCUSSION THREAD

**Discussion by Andre601** [lowlighter/metrics#1174] [Ideas]
I have an idea for 2 new options for the repository plugin I want to share:

### Most starred

`plugin_repository_starred: <number>` would display `<number>` amounts of repositories from your account, sorted by their star count.

Example config:
```yaml
name: Featured repositories
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.repositories.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_repositories: yes
  # Displays 3 repositories
  plugin_repositories_starred: 3
```

### Random

`plugin_repository_random` to display a random repository from your account.

Example config:
```yaml
name: Featured repositories
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.repositories.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  plugin_repositories: yes
  # Displays 3 repositories
  plugin_repositories_random: yes
```
