### DISCUSSION TITLE
plugin_wakatime_days defaults to 7 unexpectedly

### DISCUSSION THREAD

**Discussion by marvinscham** [lowlighter/metrics#1184] [Q&A] [answered]
Minimum example derived from [my usecase](https://github.com/marvinscham/marvinscham/blob/main/.github/workflows/metrics.yml):
```yaml
      - name: metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
          plugin_wakatime_days: 30
          plugin_wakatime_sections: time, projects-graphs, languages-graphs, editors
          plugin_wakatime_user: marvinscham
          plugin_wakatime_url: https://waka.xn--schmkerei-37a.de
```
Example [run](https://github.com/marvinscham/marvinscham/runs/7799802277) shows that the option is [properly read into env](https://github.com/marvinscham/marvinscham/runs/7799802277?check_suite_focus=true#step:3:384). Later it appears to have [defaulted to 7](https://github.com/marvinscham/marvinscham/runs/7799802277?check_suite_focus=true#step:3:842).

For context, I'm using a self-hosted instance of wakapi. I checked whether it's wakapi's API but it doesn't appear to be the issue as it works normally for the 7 days it defaults to and I checked the `metrics` `wakatime-plugin`'s url call and it works as expected:

`${url}/api/v1/users/${user}/stats/${range}?api_key=${token}`
↓
 `https://waka.xn--schmkerei-37a.de/api/v1/users/marvinscham/stats/last_30_days?api_key=omitted`

_Note: It's configured to not require an API key for that range so you can open the link and just check for yourself._

What am I doing wrong? Why does `plugin_wakatime_days` default to `7`?
