### DISCUSSION TITLE
Stargazer WorldMap not showing the data

### DISCUSSION THREAD

**Discussion by Sonichigo** [lowlighter/metrics#1219] [Q&A]
Stargazer worldmap isn't showing any data in green color. But when using Charts or Chartlist data is visible.

![image](https://user-images.githubusercontent.com/53110238/188813781-88ef6088-e4ef-45ba-8b3a-3d640a4c5de4.png)

```yml
github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_followup: yes
          plugin_followup_archived: no
          plugin_stargazers: yes  
          plugin_stargazers_charts: yes
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 250
```

How to fix this?
