### DISCUSSION TITLE
Most used languages don´t work with "indepth mode"

### DISCUSSION THREAD

**Discussion by GermanBartoli** [lowlighter/metrics#1230] [Q&A]
My code

```yml
          # Languages
          # commits_authoring: German Bartoli, bartoligerman497, bartoligerman497@users.noreply.github.com
          plugin_languages: yes
          plugin_languages_ignored: Rich Text Format, JSON, XML, TEXT, INI, Ant Build System, Microsoft Visual Studio Solution, JAR Manifest, SVG
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 30
          # plugin_languages_categories: markup, programming, prose, data
          plugin_languages_colors: github
```

before it worked correctly I don't know what happened, If I remove that mode it works but I want to activate it.

![image](https://user-images.githubusercontent.com/53313625/190444253-7d694bf8-0dc2-4070-99ee-4f2e4a8ba296.png)
