### DISCUSSION TITLE
Recently used languages don't display anything

### DISCUSSION THREAD

**Discussion by Pandicon** [lowlighter/metrics#1237] [Q&A]
I haven't touched my config for a while and I've recently noticed that the "Recently used languages" section is empty:
![image](https://user-images.githubusercontent.com/70060103/191077903-40910f9b-bd5a-46b6-a1e6-b76199788a82.png)
However, I have made several commits in the last week. All were pushed to private repositories, but that didn't cause any issues before.
The commits seem to get detected, because the commits count gets increased. Any ideas why this could happen?
I do have quite a lot of repositories (the plugin reports 95, while github shows 92, no idea why), the languages don't update even when I push to an older repo though.

**Comment by lowlighter** [comment]
Hi 👋 !

The recently used languages section use the commits that are fetched from your activity feed, so if you're very active the push events may disappear from it (like comments, issues, pr, wiki edition, repo creation, etc.), you may have some luck by increasing [`plugin_languages_recent_load`](https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md#plugin_languages_recent_load), but the available feed is usually pretty small so it may have no effect

> The commits seem to get detected, because the commits count gets increased

If you're talking about the commits count displayed in the activity section, then it's because these are separate plugins, which usually fetch their data independantly (in this case directly from GraphQL) so usually stats from different plugins are not directly related 

> I do have quite a lot of repositories (the plugin reports 95, while github shows 92, no idea why)

It could be because you set [`repositories_affiliations: ""`](https://github.com/lowlighter/metrics/blob/master/source/plugins/base/README.md#repositories_affiliations) which is the broadest affiliation possible (can be anyone you contributed on, not necessarly the one you own)

**Reply by Pandicon** [reply]
To be honest, I am not that active apart from commits :D
What I noticed though is that when I pushed changes to a public repository, it counted towards the recently used metric, while pushing to private repos didn't. I will observe it more and check if it is indeed only detecting public commits (I had it set up to count even private repositories, and it worked for a while, until it broke a few weeks ago).

**Comment by Nixinova** [comment]
Also having this problem, going back into last year.
<img width="129" alt="image" src="https://github.com/lowlighter/metrics/assets/42429413/c90e1946-a668-4e23-9c21-c6038b34bd1d">
I have recent commits.
<img width="261" alt="image" src="https://github.com/lowlighter/metrics/assets/42429413/69fe45ad-9faa-4d53-b355-ed5645fb395c">

E.g October metrics:
<img width="373" alt="image" src="https://github.com/lowlighter/metrics/assets/42429413/2cbd0cd1-5375-47ea-8d93-2e96d402cfc9">

Broke sometime between 15 Sep 18:33 https://github.com/Nixinova/Nixinova/blob/2ad5ad8e02c8e6cdacb9b8986701d7b55293b1b7/github-metrics.svg and 18 Sep 18:31 https://github.com/Nixinova/Nixinova/blob/bffe99800c2a8e60ece4d875963384838978e878/github-metrics.svg UTC 2022.

There's no commits to this repo during that time though...

<details>
<summary>Metrics yaml workflow code</summary>

```yml
name: Metrics
on:
  schedule: 
    - cron: "0 18 * * */4"
  workflow_dispatch: # enabled

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics

          template: classic
          repositories_affiliations: ''
          commits_authoring: Nixinova
          config_timezone: Pacific/Auckland # NZT

          plugin_lines: yes
          plugin_traffic: yes

          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories, user

          plugin_discussions: yes

          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming, markup
          plugin_languages_indepth: yes

          plugin_gists: yes

          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0 # disable

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
  
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_timestamps: yes

          plugin_code: yes

          plugin_reactions: yes
          plugin_reactions_details: count
          plugin_reactions_limit: 200

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 14
          plugin_wakatime_limit: 4
          plugin_wakatime_repositories_visibility: public

```

</details>
