### DISCUSSION TITLE
Secrets are unexpectedly printed in plain text in job logs

### DISCUSSION THREAD

**Discussion by tenkirin** [lowlighter/metrics#1281] [Q&A] [answered]
Hi, first of all, thanks a lot for this brilliant project!

I came across an issue and tried to solve it many times, but I cannot figure it out myself, so I decided to come here for some help.

I noticed that some private repos should not impact on the result of metrics, then I tried to use the option `repositories_skipped` with a GitHub Actions Secret as the value of it.

```YAML
template: classic
base: header
config_timezone: ${{ secrets.METRICS_TIMEZONE }}
repositories_skipped: ${{ secrets.METRICS_SKIPPED_REPO }} # THIS LINE is newly added, and the value of it is a comma-separated string of repo full handle
```

But in the job logs, the value of secret `secrets.METRICS_SKIPPED_REPO` is unexpectedly printed in plain text, rather than just the same as the one for timezone, which is a `***` string. This makes the secret meaningless and dangerous, since everyone can see job logs in the public repo.

![image](https://user-images.githubusercontent.com/60653216/201492847-170cbb1e-9ef6-4a2c-bc55-d61fc33b8101.png)

Is this a bug? Or is there an option to turn off the output of metrics?
