### DISCUSSION TITLE
Web Screenshot Plugin Issue

### DISCUSSION THREAD

**Discussion by 1RB** [lowlighter/metrics#1286] [Q&A] [answered]
Using the `Web Screenshot` plugin 

## .yml file
```yml
name: Screenshot
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  web-screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: site.screenshot.svg
          token: NOT_NEEDED

          # Options
          template: classic
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_selector: body
          plugin_screenshot_title: Inimicalpart.com
          plugin_screenshot_url: https://inimicalpart.com  
```

## README.md
```md
<img src="/site.screenshot.svg" alt="inimicalpart.com">
```

## Expected Result
![image](https://user-images.githubusercontent.com/86501179/202897019-2e882fe9-75d8-403f-be34-79fb3045f41a.png)

## Actual Result
![image](https://user-images.githubusercontent.com/86501179/202897052-56ef57a0-af9f-4034-b107-31e94614ec83.png)

**Comment by lowlighter** [comment, marked as answer]
Hi 👋 !

It'll be fixed by https://github.com/lowlighter/metrics/commit/7d7e9d63a7af66618784861c947f49691734d19d on `@master`/`@main` once the rebuild complete

The issue was that it was only listening for the "onload" event so it was taking the screenshot a bit too early.

I also added:
- #1288

So if you need to change the scale of the viewport to make it a bit bigger you can easily do it by adding
```yml
plugin_screenshot.viewport: |
  {"width":500, "height":200}
```

Which looks like this:
<img src="https://user-images.githubusercontent.com/22963968/202900480-63e547cf-efd2-4868-8e29-3b47b61c246f.png" width="400">

**Reply by 1RB** [reply]
would you mind pasting the code for 
![image](https://user-images.githubusercontent.com/86501179/202926004-81dad52f-15a2-41ba-9f62-c860a24be1b1.png)

as I'm still having troubles getting it to work

Also i'm not sure if you are aware but 
![image](https://user-images.githubusercontent.com/86501179/202926511-e2fee2e4-21e7-46fb-9172-b5f1f5859a9a.png)
it seems that it didnt get deployed to `@latest` and maybe thats why im having trouble with getting it to work

**Reply by lowlighter** [reply]
I've used the following:
```yml
      - uses: lowlighter/metrics@master # not @latest
        with:
          token: NOT_NEEDED
          template: classic
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_selector: body
          plugin_screenshot_title: Inimicalpart.com
          plugin_screenshot_url: https://inimicalpart.com
          plugin_screenshot_viewport: |
            {"width":500, "height":200}
```

> it seems that it didnt get deployed to `@latest` and maybe thats why im having trouble with getting it to work

Yeah this is the intended behaviour, the `@latest` branch is treated as the "stable" one which only reflect the latest release (v3.29 currently).
The patches are currently only present on `@master`/`@main` branches for now, which are treated as the testing branches

So you may need to switch to one of the testing branches for now, or just wait a few weeks until v3.30 is released

Hope this isn't too confusing 😅
