### DISCUSSION TITLE
plugin_[plugin]_title option

### DISCUSSION THREAD

**Discussion by Andre601** [lowlighter/metrics#1305] [Ideas]
An option to change the title of a specific plugin (or hide it completely) would be a neat addition...

For me personally, a use-case would be to have the titles of the repositories plugin hidden, as I'm already showing the SVGs under a "Repositories" header in my profile readme.

![grafik](https://user-images.githubusercontent.com/11576465/205522311-c8a9f94d-8358-4777-8019-a7b43fddbf9e.png)

To hide the titles, perhaps providing an empty String would be the best option?
Also, I'm for keeping the icons before the titles themself and just change the text (Maybe a separate option to allow changing the icons to a specific octicon? Tho, I think the pattern available for it alongside the global option should be enough).

**Comment by lowlighter** [comment]
Hi 👋 !

To be honest I feel like this is stepping too much into template territory to be provided as options (plus adding a new option just to configure title would create around 30-40 additional options in the `action.yml` ah ah 😅)

I know similar options are already offered in 3 plugins ( `plugin_introduction_title`/`plugin_sponsors_title`/`plugin_screenshot_title`) but even though I'm not found of it, the content of it really depends on the user so it might make sense in a way

Hope that it makes sense 😄 !

___

That being said, it's still possible to achieve what you're trying to do without having the hassle of setting a whole custom template fork by using the [`extras_css`](https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#extras_css) and/or [`extras_js`](https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#extras_js) options. While less elegant, these options really lets you do hacky stuff like below:

```yml
# Hide title text but keep icon
extras_css: |
  h2 { color: transparent; }

# Hide whole title
extras_css: |
  h2 { display: none; }

# Change title using String.prototype.replace(regex, content)
extras_js: |
  const title = document.querySelector("h2").innerHTML.replace(/\s*(<svg.*>[\s\S]+<\/svg>)\s*[\s\S]+/, "$1 My cool repositories")
  document.querySelector("h2").innerHTML = title
```

The last example may be a bit trickier if you have multiple plugins in same rendering, but using a more specialized css selector (like `:nth-of-type()`) should make it work
