### DISCUSSION TITLE
Possible to zoom in for website screenshot?

### DISCUSSION THREAD

**Discussion by Yohn** [lowlighter/metrics#1323] [Ideas]
I've been using the following to get a screenshot for my horoscope, and the text on the generated image is really small. Is there anyway to zoom in on the image, or possible just grab the text within a selector and use a template to display it?

````yaml
      - uses: lowlighter/metrics@latest
        name: Daily Horoscope
        with:
          filename: metrics/plugin.horoscope.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Daily Horoscope
          plugin_screenshot_url: https://www.horoscope.com/us/horoscopes/general/horoscope-general-daily-today.aspx?sign=10
          plugin_screenshot_selector: ".main-horoscope nav + p"
````

![horoscope](https://raw.githubusercontent.com/Yohn/Yohn/main/metrics/plugin.horoscope.svg)
