### DISCUSSION TITLE
Potential Issue with the `Repositories traffic` plugin

### DISCUSSION THREAD

**Discussion by megasanjay** [lowlighter/metrics#1376] [Q&A]
For some reason, my `Repositories traffic` plugin returns nothing at the workflow's end. I have also added the `repositories` tag to the `base` key. Even enabling `base_indepth` did not fix the issue.  I am not skipping any repositories in my config either.  From the workflow, I don't see any errors as well. Not sure what is going on tbh. 

```yml
 # Base content
base: header, activity, community, repositories, metadata
base_indepth: yes
repositories_affiliations: owner, collaborator, organization_member
repositories_forks: yes

 # 🧮 Repositories traffic
plugin_traffic: yes
```

Workflow logs: https://github.com/megasanjay/megasanjay/actions/runs/4117683701/jobs/7109286111
Workflow yml: https://github.com/megasanjay/megasanjay/blob/main/.github/workflows/metrics.yml

Generated image: 
![image](https://user-images.githubusercontent.com/21206996/217350407-1560efe7-a4c7-4dc2-a8f7-e01bd1642dbd.png)
