### DISCUSSION TITLE
[Recent coding habits] Language activity is not being showed

### DISCUSSION THREAD

**Discussion by Fabio-Vicente** [lowlighter/metrics#1386] [Q&A]
Hello, guys!

I tried to use the `Recent code habits` plugin to generate charts, but the `Language activity` is arriving empty.

I've done a discussion research, and realized that it have been already a [kwnow issue](https://github.com/lowlighter/metrics/discussions/370), that would be fixed on newer versions.

Anyway, i've tried the porposed solution (change action version from `@latest` to `@master`), but unsucessufuly.

Am I doing something wrong?

Here follows the code snippet:
``` yaml
...
- name: Coding Habits
  uses: lowlighter/metrics@master
  with:
    token: ${{ secrets.PAT }}
    user: Fabio-Vicente
    retries: 3
    retries_delay: 300
    retries_output_action: 5
    retries_delay_output_action: 120
    filename: coding-habits.svg
    output_action: none
    template: classic
    base: ""
    config_timezone: America/Bahia
    plugin_habits: yes
    plugin_habits_charts: yes
    plugin_habits_charts_type: classic
    plugin_habits_days: 30
    plugin_habits_from: 1000
    plugin_habits_facts: false
...
```

[Full file](https://github.com/Fabio-Vicente/Fabio-Vicente/blob/main/.github/workflows/metrics.yaml)

##### Evaluated image:

![Coding Habits image](https://raw.githubusercontent.com/Fabio-Vicente/Fabio-Vicente/5bf03dd3a9c619b2120f89f0fc993e2f76169d30/coding-habits.svg)
[Source](https://github.com/Fabio-Vicente/Fabio-Vicente/blob/metrics/coding-habits.svg)

Thanks everyboby!
