### DISCUSSION TITLE
Chess Plugin - 404 Error

### DISCUSSION THREAD

**Discussion by Ombucha** [lowlighter/metrics#1405] [Q&A] [answered]
I am getting this error while using the `chess` plugin:

```py
[
  {
    name: 'chess',
    result: { error: { message: 'API error: 404', instance: '' } }
  }
]
```

This is the code I am using:

```yaml
plugin_chess: yes
plugin_chess_platform: lichess.org
plugin_chess_token: ${{ secrets.LICHESS_TOKEN }}
```

Why am I getting this error? Anybody else facing the same issue?
