### DISCUSSION TITLE
Error during achievement plugin rendering

### DISCUSSION THREAD

**Discussion by waldner** [lowlighter/metrics#1474] [Q&A]
Here's my config (github action):

```
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          config_timezone: Europe/Madrid
          base: header
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_languages: yes
          config_order: base.header, isocalendar, achievements, languages
```

And here's the error:

```
[
  Status                                                          │ complete
  MIME type                                                       │ image/svg+xml
    {
      name: 'achievements',
      result: {
        error: {
          message: 'Unexpected error',
          instance: 'Failed to initiate total for achievement plugin'
        }
      }
    }
  ]
```

Any help appreciated.
