### DISCUSSION TITLE
Language activity in the habits plugin not appearing

### DISCUSSION THREAD

**Discussion by BenjaminHalko** [lowlighter/metrics#1504] [Q&A]
Nothing seems to appear in the Language activity section of the habits plugin:
![habits.svg](https://raw.githubusercontent.com/BenjaminHalko/BenjaminHalko/30097fd8809e013a4bed62ca2a909ddf8057b0f0/habits.svg)

GitHub Action:
```
habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: BenjaminHalko
          template: classic
          base: ""
          config_timezone: America/Vancouver
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: yes
```

I have tried both `latest` and `master`.
