### DISCUSSION TITLE
Metrics v4 draft overview

### DISCUSSION THREAD

**Discussion by lowlighter** [lowlighter/metrics#1533] [Announcements]
# Metrics v4 - Draft

> ### See https://github.com/lowlighter/metrics/pull/1542

*metrics* will undergo significant changes in next release in order to be more performant, portable, ergonomic, powerful and maintainable.

It will switch to [deno runtime](https://deno.com) and will be rewritten in TypeScript, and the way to pass options will change entirely.

## New concepts and usage

*metrics* will still be based on *plugins*, but will also introduce *actions* and *transformers*. Additionally, *templates* will now be merged with plugins, and the *presets* will offer more possibilities

The action will require a config file instead of accepting directly inputs.

### Presets

```yml
# Presets will now be "contexts" that define the default variables
presets:
  # The default presets is the one used by all plugins/transformers when none is specified
  # It's mostly options that are not plugin-specific, such as token, handle (login), timezone, etc. 
  default:
    plugins:
      token: ${{ secrets.token }}
      handle: octocat
      timezone: Europe/Paris
      logs: info
  # You can create additional presets like below, for instance one for your work account
  work:
    plugins:
       api: https://github.my-company.com
       token: ${{ secrets.token_company }}
       handle: octodog
  # Or for different repositories
  my-repo:
     plugins:
       handle: octocat/hello-world
       entity: repo
       template: repository
  # Or even use remote ones
  community: https://raw.githubusercontent.com/lowlighter/metrics/presets/community/preset.yml
```

### Plugins, actions and transformers

```yml
# Plugins are now ordered directly according to the order you define them
plugins:
  # To call a plugin, pass its "name" and configure it with "args"
  # Unless overriden, context is inherited from "presets.default", so the target user here is "octocat" for example
  - name: isocalendar
    args: 
      range: current-year
      colors: winter
    # Transforms will change the output, such as rendering GitHub emojis and formatting ths SVG XML
    transforms:
      - name: render.gemojis
      - name: format.xml
  # A same plugin can now be executed multiple times, and with different contexts
  # Here we could use the "presets.work" that is configured with a different account and token
  # Like explained before, the context is inherited, so here the target user would be "octodog"
  - name: isocalendar
    args: 
      range: current-year
      colors: winter
      preset: work
      timezone: Europe/London
  # You will also be able to use custom plugins, or even specific versions of a plugin
  - name: https://raw.githubusercontent.com/lowlighter/metrics/v4.0/source/plugins/isocalendar/mod.ts

  # ... actions
```
### Actions

```yml
  # plugins ... 

  # Actions are "special plugins" (denoted with a "@") that have side effects
  # For example, @render will merge the output of previous plugins into a single SVG
  - name: @render
    args:
       format: svg
    transforms:
     - name: svg.resize
  # And @publish.commit will commit the output on the repository
  - name: @publish.commit
    args:
      filename: metrics.svg
      branch: metrics 
  # It'll also be possible to reuse the same data within the same flow to publish it into differents forms, 
  # without making further API requests
  - name: @render
    args:
       format: json
  - name: @publish.commit
    args:
      filename: metrics.json
      branch: metrics 
```

### Web server

The web server will behave similarly, except that presets cannot be defined on the fly (they need to be defined by the administrator).
The syntax will ba a lax-YAML one:

```
https://metrics.dev/octocat?plugins=[{name:isocalendar, args:{range:full-year}}, {name:@render}]
```

## Privacy and security

The new version will retest all plugins with GitHub fine-grained token, in order to make sure they're compatible (and are able to properly handle missing scopes without dying) to give users more control on how their data are accessed and processed.

As it'll be based on deno, security flags will superseed `extras.features` option and be even more powerful.
For example you will be able to run *metrics* with `--allow-net=api.github.com --allow-write=/tmp --allow-run=git,licensed` to ensure your data are not leaded anywhere. 
You'll be able to run external plugins (and even official ones) with a peaceful mind.

## Portability

The new engine is designed to be extremely versatile and can be run more easily as standalone.
It'll be able to be run as a GitHub action and server (like currently), and a proper CLI will be offered later one (maybe even a single binary thanks to `deno compile`, but to be seen) 

The new engine is expected to uncouple the dependencies on base/core plugins to not only make rendering faster, but also to make it possible to be able to run metrics on serverless services - such as Vercel or Deno deploy - for most plugins (some time/cpu intensive ones, or binaries-based one probably won't make the cut though).

Setting up *metrics* will also be more easy, as the only requirement will be to install the deno runtime (single executable).
As plugin dependencies are URL based, native tree-shaking will also users to not download all dependencies requiring minimal setup and configuration.

## Reusability

*metrics* will also be designed so that third-parties app and scripts can plug to it directly:
```ts
import isocalendar from "https://raw.githubusercontent.com/lowlighter/metrics/v4.0/source/plugins/isocalendar/mod.ts"

const data = await isocalendar.run({token:Deno.env.get("GITHUB_TOKEN")})
```

This will (hopefully) increase contributors engagement and expand the *metrics* ecosystem to make it more accessible and maintainable, in the hope that this project can live on even with me not being around

Also, thanks to decentralized dependencies, plugins authors will now be able to load any external dependency (or even load a different version of a dependency).
Since deno only load dependency at upon usage, they won't impact performance and size of the app.

For example the RSS plugin:
```ts
// Imports
import { is, Plugin} from "@plugin"
import RSS from "y/rss-parser@3.13.0"

/** Plugin */
export default class extends Plugin {

  /** Name */
  readonly name = "🗼 Rss feed"

}
```

## Stability and new features

Plugins will be retested as they're being migrated, and they'll be simplified.
Templates will also be simplified/normalized in order to be both lightweight and easily editable using injected CSS / JS (similarly to `extras.css` and `extras.js` options)

New options and features will also be progressively added during this refactor (see migration guide below)

## Inputs and outputs validation

Data validation will be delegated to [Zod](https://zod.dev), which is able to both validate content at runtime but also infer typing during developpment. In addition, *metrics* will start normalizing and validating outputs, which mean that plugins results can be safely used in other applications.

`metadata.yml` will be removed, but documentation will still be generated (probably using [zod-to-json-schema](https://github.com/StefanTerdell/zod-to-json-schema))

Below is an example of data validation looks like:
```ts
/** Plugin */
export default class extends Plugin {

  /** Name */
  readonly name = "📅 Isometric commit calendar"
 
  /** Inputs */
  readonly inputs = is.object({
    range:is.union([is.literal("half-year"), is.literal("full-year"), is.literal("current-year"), is.coerce.number().int().min(1970)]).default("half-year").describe('Time range. Use `"half-year"` to display last 180 days, `"full-year"` to display last year, `"current-year"` to display this year, or use a `number` to display a specific year.'),
    colors:is.enum(["auto", "halloween", "winter"]).default("auto").describe("Color scheme"),
  })

  /** Outputs */
  readonly outputs = is.object({
    colors:is.enum(["default", "halloween", "winter"]).describe("Color scheme"),
    average:is.number().min(0).describe("Average number of commits per day"),
    max:is.number().int().min(0).describe("Highest number of commits in a single day"),
    streak:is.object({
      max:is.number().int().min(0).describe("Highest number of consecutive days with commits"),
      current:is.number().int().min(0).describe("Current number of consecutive days with commits"),
    }).describe("Streak statistics"),
    range:is.object({
      start:is.date().describe("Start date"),
      end:is.date().describe("End date"),
    }).describe("Displayed range"),
    weeks:is.array(is.object({days:is.array(is.object({count:is.number().int().min(0), level:is.number().min(0).max(4)}).nullable())})).describe("List of weeks"),
  })

  /** Action */
  async action({handle}:Plugin["context"]) {
    const {range, ...inputs} = await this.inputs.parseAsync(this.context.args)
    /* ... */
    return result
  }

}
```

## Improved testing and coverage

Currently, testing metrics is pretty painful as we need to rebuild the docker container, spawn a fake web instance and simulate different environments against it. It's hyper slow (~30 min) which is also frustrating.

Thanks to the engine rework, it's now insanely faster, and we're also able to provide code coverage.
Data mocking has also been reworked to be way less hacky than currently, making it also more robust for testing:

![](https://github.com/lowlighter/metrics/assets/22963968/e99fdd20-8037-4bfa-9f34-492950eba436)

TypeScript and linting will prevent basic errors.

PRs will be integrated better with serverless application to offer proper previewing.

## What for now ?

There is no ETA for this, but a pre-release will eventually come out as I'm rewritting the engine.
v3.35 will probably just be replaced by v4

Once the engine is rewritten with a few plugins, the rest of features will be progressively migrated until v4 is on par with v3.
I'll accept PRs for plugins migrations (and if you're interested to eventually be a maintainer in the future, let me know)

*metrics.lecoq.io* will probably be migrated to either Deno deploy or Vercel, and even if `@main`/`@master`/`@latest` are bumped to v4, a "configuration transpiler" will be implemented (which will also be offered to users to convert to the future new config format).

I'm still experimenting with what can be done, but I'm open to feedback.

The migration guide below will also act as a progress list

Thanks for reading up until there 💕 !
