### DISCUSSION TITLE
Most used languages section not displaying anything

### DISCUSSION THREAD

**Discussion by eduardosantoshf** [lowlighter/metrics#1549] [Q&A]
Hi!

A few weeks ago, I noticed that the "Most recent languages" section is not displaying anything. 
I haven't changed anything, neither my workflow nor permissions.

My workflow file:
```yaml
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          base_indepth: yes

          # Options
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, php, roff, xslt
          plugin_languages_details: percentage
          plugin_achievements: no
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
```

My generated metrics file:

![github-metrics](https://github.com/lowlighter/metrics/assets/45774025/f0336b38-f64b-44a3-895e-13d3fbf0afdc)
