### DISCUSSION TITLE
Action not running

### DISCUSSION THREAD

**Discussion by keplerHaloxx** [lowlighter/metrics#1589] [Q&A]
I’m trying to setup actions with this yml file
```yml
name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: keplerHaloxx

          template: classic
          config_display: columns
          base: header, activity, community, repositories
          commits_authoring: keplerHaloxx
          config_timezone: Australia/Melbourne
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 64
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_reactions_limit: 200
          plugin_reactions_limit_issues: 100
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_year: current-year
          plugin_traffic: yes
          repositories_forks: yes
```
I don’t know what to do as i mostly copied the yml file from a different guys profile
