### DISCUSSION TITLE
16personalities not rendering: Unexpected error

### DISCUSSION THREAD

**Discussion by tuc0w** [lowlighter/metrics#1601] [Q&A]
I just added the 16personalities plugin to my metrics and instantly getting an "Unexpected error" during the rendering.

This is my config and the secret is set correctly:
```yaml
# 16personalities
plugin_16personalities: yes
plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
plugin_16personalities_sections: personality, profile, traits
plugin_16personalities_scores: yes
```

This is the error log:
```
[
  {
    name: '16personalities',
    result: {
      error: {
        message: 'Unexpected error',
        instance: Error [TypeError]: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
            at evaluate (evaluate at Object.default [as 16personalities] (file:///metrics/source/plugins/community/16personalities/index.mjs:23:28), <anonymous>:1:13)
            at #evaluate (file:///metrics/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:251:19)
            at async ExecutionContext.evaluate (file:///metrics/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:148:16)
            at async Object.default [as 16personalities] (file:///metrics/source/plugins/community/16personalities/index.mjs:23:17)
            at async file:///metrics/source/plugins/core/index.mjs:67:30
            at async Promise.all (index 1)
            at async metrics (file:///metrics/source/app/metrics/index.mjs:81:22)
            at async retry.retries.retries (file:///metrics/source/app/action/index.mjs:407:40)
            at async retry (file:///metrics/source/app/action/index.mjs:57:22)
            at async file:///metrics/source/app/action/index.mjs:406:28
      }
    }
  }
]
```

I am using the latest tag so the action should be up to date.

Any idea what could cause the problem?
