### DISCUSSION TITLE
Languages plugin indepth analysis failed

### DISCUSSION THREAD

**Discussion by RenovZ** [lowlighter/metrics#1602] [Q&A]
The code.
```yaml
name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: metrics-production
    permissions:
      contents: write
    steps:
      - name: Most used
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
      - name: Indepth analysis
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
```

The log:
<img width="926" alt="image" src="https://github.com/lowlighter/metrics/assets/6456505/686deea0-9247-49a5-9449-dbb7bce6a896">

Except `Indepth analysis` step, others works fine.
