### DISCUSSION TITLE
Delete workflows with Action

### DISCUSSION THREAD

**Discussion by Long18** [lowlighter/metrics#1604] [Q&A] [answered]
In my GitHub repository, I've implemented a workflow using GitHub Actions to automatically remove expired or unnecessary workflow runs. Currently, I'm utilizing the following workflow:

```yaml
name: Remove expired workflow runs
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  remove-expired-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run cleanup script
        run: ./delete_workflows.sh owner/repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

And here's the accompanying script (delete_workflows.sh) I'm using: https://github.com/lowlighter/metrics/blob/master/.github/actions/ghcr-clean/delete_workflows.sh

Could anyone provide feedback on this workflow setup and script for efficiently managing workflow runs within a GitHub repository? Thank you!
