### DISCUSSION TITLE
my Achievements plugin wasn't work with Unexpected error

### DISCUSSION THREAD

**Discussion by falconlee236** [lowlighter/metrics#1607] [Q&A]
my Achievements plugin wasn't work with Unexpected error
### My workflow file
```yml
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stackoverflow.svg
          token: NOT_NEEDED
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 12867943
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 3
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode_user: "falconlee236"
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories, achievements, stackoverflow, leetcode
          plugin_lines: yes

# https://metrics.lecoq.io/insights?user=falconlee236
```
my workflow file is under presented and other plugin was working well,  
but Achievements plugin wasn't work with Unexpected error
### My svg file
<img width="944" alt="image" src="https://github.com/lowlighter/metrics/assets/52999093/ea92f5d7-ac00-4c46-9ed3-c8ced0d5e618">

__how can i do for this error? Please help me__
