### DISCUSSION TITLE
Contribution added, removed reported as 0 on repository template

### DISCUSSION THREAD

**Discussion by kaestro** [lowlighter/metrics#1615] [General]
Hello. Before starting, thank you for the wonderful plugin!

I really love the designs and idea of what metrics gives. I've always wondered how I may express my  works on the github repositories and this solved my problem!

But for the problem I'm having right now is that the repository template is not working properly, that it's showing added/removed lines as 0 as following.

![image](https://github.com/lowlighter/metrics/assets/32026095/a8e3c806-6ba1-4037-85e0-ba6a604a0154)

![image](https://github.com/lowlighter/metrics/assets/32026095/d62bc9cf-be6c-4bab-bfc7-06f18d3abd8b)

it might be of my problem and my metrics yml is as follows

```yaml
name: Get Lowlighter metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main", "1-apply-lowlighter-metrics"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - uses: lowlighter/metrics@main
        with:
          template: repository
          filename: metrics.chatapplication.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: ChatApplication
          plugin_lines: yes
          plugin_followup: yes

      - uses: lowlighter/metrics@main
        with:
          template: repository
          filename: metrics.blog.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: kaestro.github.io
          plugin_lines: yes
          plugin_followup: yes

      - uses: lowlighter/metrics@main
        with:
          template: repository
          filename: metrics.algorithms.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaestro
          repo: algorithms_v3
          plugin_lines: yes
          plugin_followup: yes
```

and you can get the look on log from [here](https://github.com/kaestro/kaestro/actions/runs/8777073711/job/24122500564)

any guess which is problem? Have I written the workflow file in a wrong way?
