### DISCUSSION TITLE
Licenses plugin: unsupported context user

### DISCUSSION THREAD

**Discussion by amedee** [lowlighter/metrics#1616] [Q&A]
I'm running Metrics as a GitHub Action.

I have one error in rendering, with the Licenses plugin:
```
Rendering                                                       │  
1 error(s) occurred
  [
    {
      name: 'licenses',
      result: {
        error: {
          message: 'Unsupported context user',
          instance: Error
              at meta.inputs (file:///metrics/source/app/metrics/metadata.mjs:118:81)
              at Object.default [as licenses] (file:///metrics/source/plugins/licenses/index.mjs:10:67)
              at file:///metrics/source/plugins/core/index.mjs:67:57
              at Object.default [as core] (file:///metrics/source/plugins/core/index.mjs:80:7)
              at default (file:///metrics/source/templates/classic/template.mjs:4:25)
              at metrics (file:///metrics/source/app/metrics/index.mjs:80:11)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async retry.retries.retries (file:///metrics/source/app/action/index.mjs:407:40)
              at async retry (file:///metrics/source/app/action/index.mjs:57:22)
              at async file:///metrics/source/app/action/index.mjs:406:28
        }
      }
    }
  ]
Status                                                          │ complete
MIME type                                                       │ image/svg+xml
```

This is my workflow file:

```
name: Metrics
on:
  # Schedule daily updates
  schedule: [ { cron: "0 0 * * *" } ]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      actions: write
      contents: write
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Brussels
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_condition: data-changed
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_licenses: yes
          plugin_stars: yes
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_people: yes
          plugin_achievements: yes
          plugin_activity: yes
          plugin_calendar: yes
          plugin_notable: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 766786
          plugin_rss: yes
          plugin_rss_source: https://amedee.be/feed/
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
```

My repos mostly have MIT license and some LGPL.
Some repos are without license.

Am I missing something in my config?
