### DISCUSSION TITLE
achievement not as expected

### DISCUSSION THREAD

**Discussion by wanghaisheng** [lowlighter/metrics#1637] [Q&A]
```
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, sponsor, deployer, member, maintainer, developer,scripter, packager, explorer, infographile, manager
```
from https://metrics.lecoq.io/insights?user=wanghaisheng i found this 

![image](https://github.com/user-attachments/assets/0fc428f0-32b5-4b56-b5d4-6049f8061e88)

what i actually got is 
![image](https://github.com/user-attachments/assets/a69c02bf-429e-4aae-81e5-0175ade92113)

where does those Great inspirer come from
