### DISCUSSION TITLE
How to generate metrics for dark theme?

### DISCUSSION THREAD

**Discussion by Vncntvx** [lowlighter/metrics#1663] [Q&A]
I am using metrics generated charts in my homepage, but my homepage has both light and dark modes, now the charts perform well in light mode and lack visibility in dark mode, how to specify the color theme.

**Comment by EchoSingh** [comment]
To customize metrics charts for dark themes, you can add the following snippet to your code to specify custom colors. Replace `green` with your preferred color to suit your dark theme:

```yml
steps:
  - uses: lowlighter/metrics@v3.20
    with:
      template: markdown
      filename: README.md
      extras_css: |
        div.field { color: green !important; }
        h2.field { color: green !important; }
```
This approach allows you to fine-tune the color styling of your charts for better visibility in dark mode.

If this resolves your issue, kindly mark this question as answered. 😊
