### DISCUSSION TITLE
workflow does not end after saving

### DISCUSSION THREAD

**Discussion by andry81** [lowlighter/metrics#1668] [Q&A] [answered]
workflow:

```
on:
  schedule:
    - cron: "0 */24 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Basic lecoq metrics
        uses: lowlighter/metrics@latest
        with:
          template: classic

          base: header, repositories

          base_indepth: true

          repositories_affiliations: owner, collaborator, organization_member

          token: ${{ secrets.METRICS_LECOQ_TOKEN }}

          # required for `output_condition: data-changed`
          config_output: svg

          config_timezone: Europe/Moscow

          filename: repo/andry81/andry81/stickers/readme-stats/metrics-lecoq.svg

          output_action: commit
          output_condition: data-changed

          committer_token: ${{ github.token }}
          committer_message: 'A/U: update ${filename}'
```

The `secrets.METRICS_LECOQ_TOKEN` has `public_repo` permissions.

I have to cancel the workflow to stop it.

The workflow output:

```
Metrics                                                         │  
Setup                                                           │ complete
Version                                                         │ 3.34.0
Using prebuilt image                                            │ true
Debug mode                                                      │ false
Debug flags                                                     │ (none)
GitHub token                                                    │ (provided)
GitHub token format                                             │ classic
GitHub GraphQL API                                              │ ok
GitHub GraphQL API endpoint                                     │ (default)
GitHub REST API                                                 │ ok
GitHub REST API endpoint                                        │ (default)
API requests (REST)                                             │ 4990/5000 (200+ required)
API requests (GraphQL)                                          │ 4995/5000 (200+ required)
API requests (Search)                                           │ 30/30
Token validity                                                  │ seems ok
GitHub account                                                  │ andry81
Current repository                                              │ andry81/actions--gh-cache
Committer token                                                 │ (provided)
Committer branch                                                │ master
Committer head branch                                           │ master
Committer REST API                                              │ ok
Committer account                                               │ (github-actions)
Committer head branch status                                    │ ok
Previous render sha                                             │ (none)
SVG output                                                      │ repo/andry81/andry81/stickers/readme-stats/metrics-lecoq.svg
SVG optimization                                                │ css, xml
SVG verification after generation                               │ false
────────────────────────────────────────────────────────────────────────────────────────
Templates                                                       │  
Community templates                                             │ (none)
Template used                                                   │ classic
Query additional params                                         │ {}
────────────────────────────────────────────────────────────────────────────────────────
Core                                                            │  
Markdown template path                                          │ TEMPLATE.md
Extra CSS                                                       │ 
Extra JavaScript                                                │ 
Timezone for dates                                              │ Europe/Moscow
Plugin order                                                    │ 
Use twemojis                                                    │ false
Use GitHub custom emojis                                        │ true
Use GitHub octicons                                             │ false
Display width (for image output formats)                        │ regular
Use CSS animations                                              │ true
Base64-encoded images                                           │ true
Output padding                                                  │ 0, 8 + 11%
Output format                                                   │ svg
Configuration presets                                           │ 
Notice about new releases of metrics                            │ true
Experimental features                                           │ 
Plugin errors                                                   │ (displayed in generated image)
────────────────────────────────────────────────────────────────────────────────────────
Base content                                                    │  
Fetched repositories                                            │ 100
Indepth mode                                                    │ false
Show `Available for hire!` in header section                    │ false
Skip base content                                               │ false
Fetched repositories per query                                  │ 100
Include forks                                                   │ false
Repositories affiliations                                       │ owner,collaborator,organization_member
Default skipped repositories                                    │ 
Default ignored users                                           │ github-actions[bot],dependabot[bot],dependabot-preview[bot],actions-user,action@github.com
Identifiers that has been used for authoring commits            │ .user.login
Base sections                                                   │ header, repositories
────────────────────────────────────────────────────────────────────────────────────────
Rendering                                                       │  
Status                                                          │ complete
MIME type                                                       │ image/svg+xml
────────────────────────────────────────────────────────────────────────────────────────
Saving                                                          │  
Output condition                                                │ data-changed
Previous hash                                                   │ null
Current hash                                                    │ 000ac45de725c843d20eab8504d80efa
Content changed                                                 │ true
Save to /metrics_renders/repo/andry81/andry81/stickers/readme-stats/metrics-lecoq.svg │ ok
Output action                                                   │ commit
Current render sha                                              │ e832e11643260530f3dda9f89f2333a55d8deb63
```

**Comment by andry81** [comment, marked as answer]
Seems the reason was in the `contents` permission parameter.

Instead of:

> &#x25BE; GITHUB_TOKEN Permissions
> &nbsp;&nbsp;&nbsp;&nbsp;Contents: read
> &nbsp;&nbsp;&nbsp;&nbsp;Metadata: read
> &nbsp;&nbsp;&nbsp;&nbsp;Packages: read

Must be:

> &#x25BE; GITHUB_TOKEN Permissions
> &nbsp;&nbsp;&nbsp;&nbsp;Contents: write
> &nbsp;&nbsp;&nbsp;&nbsp;Metadata: read

To fix:

```
jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write
```

Details:

https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication

*Note*:

There is can be another infinite loop:

https://github.com/lowlighter/metrics/issues/152

> * https://github.com/lowlighter/metrics/commit/c0f03635311ef727c7d40e15a8fc62f9091846ba Add `committer_message` option to use custom commit messages
>   * If using `commiter_token` different from `GITHUB_TOKEN`, ensure you add `[Skip GitHub Action]` or handle correctly workflows skip to prevent infinite loop

In mine case it fixes the infinite loop irrespectively to the `[Skip GitHub Action]` presence in the `committer_message`.
