### DISCUSSION TITLE
Error: Resource not accessible by integration

### DISCUSSION THREAD

**Discussion by JitishxD** [lowlighter/metrics#1680] [Q&A] [answered]
## Whenever I run my workflow it ends up with Resource not accessible by integration and i have no idea why this happens
![image](https://github.com/user-attachments/assets/7cac6f3e-cdde-470a-938a-90ce0c40f19d)

## below is my workflow code

```
name: Update GitHub Metrics
on:
  # Schedule updates (each day)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: JitishxD
          template: classic
          base: ""
          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          # plugin_languages_ignored: html
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 1000
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          commits_authoring: JitishxD, Jitishxd@users.noreply.github.com
          plugin_languages_details: lines, percentage
          plugin_languages_other: no
          repositories_skipped: |
            JitishxD/forge-api-docs
```
