### DISCUSSION TITLE
Plugin: YouTube Music Error with Playlist Integration

### DISCUSSION THREAD

**Discussion by ghost** [lowlighter/metrics#1684] [Q&A] [answered]
I am attempting to integrate YouTube Music into my metrics setup using the following configuration:

plugin_music: yes
plugin_music_provider: youtube
plugin_music_playlist: https://www.youtube.com/playlist?list=PLd2ArdZjOMpYqzmRD-QMgEzdN5RuCXE

However, the plugin does not seem to work as expected. I have checked similar discussions and resources but could not find a resolution.

**Comment by EchoSingh** [comment, marked as answer]
The issue arises because a standard **YouTube URL** was provided instead of a **YouTube Music URL**. To resolve this, follow these steps:

## Correcting the URL
1. Open the playlist in [YouTube Music](https://music.youtube.com/).
2. Copy the **YouTube Music URL** from the browser's address bar. It should look like:

## Correct Configuration
Update your configuration file to include the correct **YouTube Music URL**. Here’s how it should look:

```yaml
plugin_music: yes
plugin_music_provider: youtube
plugin_music_playlist: YouTube Music URL
```

**Comment by ghost** [comment]
@EchoSingh 

help me to delete the workflow 

my code 

```run.yml
name: Metrics
on:
  schedule: [ { cron: "0 0 * * *" } ]
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      actions: write
      contents: write
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_condition: data-changed
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_licenses: yes
          plugin_stars: yes
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_people: yes
          plugin_achievements: yes
          plugin_activity: yes
          plugin_calendar: yes
          plugin_notable: yes
```

**Comment by EchoSingh** [comment]
use like this 

```yml
ame: Metrics
on:
  schedule: [ { cron: "0 0 * * *" } ]
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      actions: write
      contents: write
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_condition: data-changed
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_licenses: yes
          plugin_stars: yes
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_people: yes
          plugin_achievements: yes
          plugin_activity: yes
          plugin_calendar: yes
          plugin_notable: yes
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
```
