### DISCUSSION TITLE
How to add different username for anilist

### DISCUSSION THREAD

**Discussion by congaterori** [lowlighter/metrics#265] [Q&A] [answered]
Hello i have different username in github and anilist i don't want to change name in github is congaterori and in anilist is johnny20061234

My code please edit

```
name: Metrics

  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.TOKEN }}
          user: johnny20061234
          #template: classic
          #base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          plugin_anilist: yes
          plugin_anilist_limit.characters: 22
          plugin_anilist_limit: 2
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
```
