### DISCUSSION TITLE
How to add different username for anilist

### DISCUSSION THREAD

**Discussion by congaterori** [lowlighter/metrics#269] [Q&A] [answered]
**My username anilist is johnny20061234 and my github username is congaterori**
i don't want to change name
this is my code please edit

```
# This is a basic workflow to help you get started with Actions
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.TOKEN }}
          user: congaterori
          template: classic
          #base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          plugin_anilist: yes
          plugin_anilist_limit.characters: 22
          plugin_anilist_limit: 2
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
```

**Comment by lowlighter** [comment, marked as answer]
Hello 🙂 

The following should work:
```yml
with:
  user: congaterori
  plugin_anilist_user: johnny20061234
```
