### DISCUSSION TITLE
Change color of text

### DISCUSSION THREAD

**Discussion by AdityaKane2001** [lowlighter/metrics#279] [Q&A] [answered]
How do we change the color of the text in the image? The usual dark blue and grey colors are a bit off. Would like to use a bit of light colors against the dark background.
Thanks

**Comment by lowlighter** [comment, marked as answer]
You can add custom CSS using this option:
https://github.com/lowlighter/metrics/blob/a2dda44d9c2fd6988a259ef872a59900ae5fac0b/source/plugins/core/metadata.yml#L128-L137

If you need to edit more than text colors, then it's probably better to just fork this repository and edit [source/templates/classic/style.css](https://github.com/lowlighter/metrics/blob/master/source/templates/classic/style.css)

**Reply by AdityaKane2001** [reply]
Where exactly should I add this CSS?
And no, I just want to change these font colors

**Reply by lowlighter** [reply]
Something along this should works:
```yaml
- uses: lowlighter/metrics@master
  with:
    # ...
    extras_css: |
      div.field { color: white !important; }
      h2.field { color: blue !important; }
 ```
But this feature is only available on `@master` it hasn't been released yet on `@latest` (will be in v3.8) 

For quick testing you can open the svg in your browser and edit css rules manually to check how it'll render
