### DISCUSSION TITLE
GitHub Action fails (json output)

### DISCUSSION THREAD

**Discussion by lucyydotp** [lowlighter/metrics#361] [Q&A] [answered]
```
Run lowlighter/metrics@latest
Metrics docker image setup
────────────────────────────────────────────────────────────────────────────────────────
Metrics                                                  │  
Setup                                                    │ complete
Version                                                  │ 3.10.0
Using prebuilt image                                     │ true
Debug mode                                               │ false
Debug flags                                              │ (none)
GitHub token                                             │ (provided)
Github GraphQL API                                       │ ok
Github REST API                                          │ ok
Token validity                                           │ seems ok
GitHub account                                           │ lucyy-mc
Current repository                                       │ lucyy-mc/lucyy-mc
Committer token                                          │ (provided)
Committer branch                                         │ main
Committer head branch                                    │ main
Committer REST API                                       │ ok
Committer account                                        │ (github-actions)
Committer head branch status                             │ ok
Previous render sha                                      │ (none)
SVG output                                               │ github-metrics.json
SVG optimization                                         │ true
SVG verification after generation                        │ false
────────────────────────────────────────────────────────────────────────────────────────
Templates                                                │  
Community templates                                      │ (none)
Template used                                            │ classic
Query additional params                                  │ {}
────────────────────────────────────────────────────────────────────────────────────────
Core                                                     │  
Rendered markdown output path                            │ TEMPLATE.md
Extra CSS                                                │ 
Timezone used                                            │ Europe/London
Configure content order                                  │ (none)
Use twemojis instead of emojis                           │ false
Use GitHub custom emojis                                 │ true
Render display width                                     │ regular
SVG CSS animations                                       │ true
Image padding                                            │ 0, 11%
Output image format                                      │ json
Experimental features                                    │ (none)
Plugin errors                                            │ (displayed in generated image)
────────────────────────────────────────────────────────────────────────────────────────
Base content                                             │  
Number of repositories to use                            │ 100
Include forks in metrics                                 │ true
Repositories affiliations                                │ owner
Default repositories to skip                             │ (none)
List of surnames or email addresses you use when authoring commits │ .user.login
Base sections                                            │ header, activity, community, repositories, metadata
────────────────────────────────────────────────────────────────────────────────────────
Rendering                                                │  
Status                                                   │ complete
────────────────────────────────────────────────────────────────────────────────────────
Saving                                                   │  
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
────────────────────────────────────────────────────────────────────────────────────────
    at new NodeError (node:internal/errors:329:5)
    at Function.from (node:buffer:323:9)
    at file:///metrics/source/app/action/index.mjs:312:67 {
  code: 'ERR_INVALID_ARG_TYPE'
}
undefined
An error occured, logging debug message :
TypeError: Cannot read property 'oid' of null
    at file:///metrics/source/app/action/index.mjs:208:36
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Attempt 1/3
Error: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
Error: Process completed with exit code 1.
```

I keep on getting this error whenever I try to run the action. Here's my config file:
```yaml
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.STATS_TOKEN }}

          # Options
          user: lucyy-mc
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          repositories_forks: yes
          config_output: json
```
          
Anyone have any ideas of what I'm doing wrong? Thanks in advance
