### DISCUSSION TITLE
Recent coding habits is Empty

### DISCUSSION THREAD

**Discussion by theory** [lowlighter/metrics#370] [Q&A] [answered]
Hello, thanks for the groovy tool.

In my [config](/theory/theory/blob/main/.github/workflows/profile.yml#L47-L51) I have setup the habits plugin as follows:

``` yaml
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 90        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
```
The header appears in [the SVG](/theory/theory/blob/main/github-metrics.svg), but there's nothing below it. Have I misconfigured something?

Thanks,

David
