### DISCUSSION TITLE
Did you forget to run actions/checkout before running your local action?

### DISCUSSION THREAD

**Discussion by AnuragAnalog** [lowlighter/metrics#448] [Q&A] [answered]
I am getting the following error when I am trying to set up the metrics in my readme file.

Error is: **Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/AnuragAnalog/AnuragAnalog/main'. Did you forget to run actions/checkout before running your local action?**

I have a main branch in my repository and the code in the action.yml file is

```yaml
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: AnuragAnalog/AnuragAnalog@main
      # If you make changes on your fork, be sure not leave @latest as tag!
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
```

My Username is: AnuragAnalog
Repo name is: AnuragAnalog
The branch name is: main

**Comment by lowlighter** [comment, marked as answer]
Hello 🙂 

The `uses` in workflows is used to tell GitHub which action you want to use. So in this case, to use metrics you need one of the following instead:
```yml
- uses: lowlighter/metrics@latest   # use latest released version
- uses: lowlighter/metrics@master   # use beta version (less stable than @latest)
- uses: lowlighter/metrics@main     # (alias for @master)
- uses: AnuragAnalog/metrics@master # use your own fork (if you want to fork it)
```

The `uses` don't point to the target repo, as you need to create the workflow file in the target repo anyway, so GitHub (and this action) already know on which repository it needs to perform actions
