### DISCUSSION TITLE
Community Templates

### DISCUSSION THREAD

**Discussion by ezeholz** [lowlighter/metrics#452] [Q&A] [answered]
Hey! So, I'm trying to make my own template work, but every time I try, there's this error that I can't debug
![image](https://user-images.githubusercontent.com/30635862/128274198-36cb2a10-4d2f-4555-a364-88b4a4d23685.png)
It's before everything loads up, even debug itself.
I'm probably doing something wrong in the templates files. This is my metadata:
```yaml
name: "📗 Bigger template"
extends: classic  # Fallback to "classic" template "template.mjs" if not trusted
index: ~          # Leave as it (this is used to order plugins on metrics README.md)
supports:
  - user          # Support users account
  - organization  # Support organizations account
formats:
  - svg           # Support SVG output
  - png           # Support PNG output
  - jpeg          # Support JPEG output
  - json          # Support JSON output
```
I tried `index` with value 4 and the same error appears.

**Comment by lowlighter** [comment, marked as answer]
Hello!

Indeed, seems that metadata weren't correctly loaded for community templates. 
It should be fixed with c5af923.

If you still encounter problems, you can use your forked action instead to avoid being blocked by this issue 🙂 

___

I tested with the following:
![image](https://user-images.githubusercontent.com/22963968/128312768-7779da95-60ef-49d4-845a-b80284c8f56f.png)

```yml
uses: lowlighter/metrics@master
with:
  token: ${{ secrets.TOKEN }}
  template: "@community"
  setup_community_templates: lowlighter/test@master:community
```
