### DISCUSSION TITLE
Error with metric action

### DISCUSSION THREAD

**Discussion by slowy07** [lowlighter/metrics#515] [Q&A] [answered]
hey,sorry for disturb again, i have aome problem with action with output with after i change the config display and output is 
```
Error: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `0403:2FD0:7A56B3:106B7EF:6132813F` when reporting this issue."}]}
Error: Process completed with exit code 1.
```
and i get back to previous, but still same erroe,may i wrong or something i miss?
this my configuration file
```yaml

name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: display_information_1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.MATRICS }}
          user: slowy07
          # template
          template: classic
          # base
          base: activity, community, repositories, metadata
          # timezone
          config_timezone: Asia/Jakarta
          # filename
          filename: github-metrics.svg
          # programming language
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: my-testing-repo
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%
          plugin_languages_limit: 15
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: no
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 7
          commits_authoring: arfy slowy
          # coding habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          # line of code changed
          plugin_lines: yes
          # topics
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          # recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          config_padding: 0, 8 + 1%
          
      # notable contrib
      - name: display_contribution
        uses: lowlighter/metrics@latest
        with:
          filename: contribution.svg
          token: ${{ secrets.MATRICS }}
          base: metadata
          plugin_notable: yes
          repositories_batch: 5
          config_padding: 0, 8 + 1%
```
thanks !!!
