### DISCUSSION TITLE
Stackoverflow plugin generation error

### DISCUSSION THREAD

**Discussion by AthulMuralidhar** [lowlighter/metrics#571] [Q&A] [answered]
- I am pretty new to workflows and i was trying them out with this on github marketplace
- i've been using stackoverflow and i thought it would be a nice edition to my readme
- here's my yml action
```yml
      - name: 🗨️ Stackoverflow
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stackoverflow.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 8689681
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
```

here is the generated file:
https://github.com/AthulMuralidhar/AthulMuralidhar/blob/main/metrics.plugin.stackoverflow.svg
- frankly i do not know who this is referring to :/ please fix
