### DISCUSSION TITLE
[3.16.0][plugins/notable]`plugin_notable_repositories` option is ignored

### DISCUSSION THREAD

**Discussion by s-takehana** [lowlighter/metrics#670] [Q&A] [answered]
`plugin_notable_repositories` option is ignored only when `plugin_notable_repositories`  + `plugin_notable_from: all`.

```yaml
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
```

Is this a bug?
