### DISCUSSION TITLE
Advanced filter for the `activity` plugin

### DISCUSSION THREAD

**Discussion by EndBug** [lowlighter/metrics#692] [Ideas]
Hi, I was thinking that it could be useful to maybe allow a more advanced filtering for the events of the `activity` plugin.

My use case would be filtering out PRs opened by Dependabot, since every week my "recent activity" tab gets flooded with merged Dependabot PRs, and nothing else can be seen :/

**Comment by lowlighter** [comment]
Hello 🙂 !

I think we could opt for an option similar to what other plugins already have, like below:
```yaml
# Ignored contributors (useful to ignore bots users)
  plugin_contributors_ignored:
    description: Contributors to ignore
    default: github-actions[bot], dependabot[bot], dependabot-preview[bot]
```

I'm open to additional filters too but I'd like to avoid the ones that are too tightly bound to a single type of event (unless it's something really wanted)
