### DISCUSSION TITLE
`config.output=json` stops working

### DISCUSSION THREAD

**Discussion by Andre601** [lowlighter/metrics#715] [Q&A] [answered]
I'm currently in the process of trying to setup a GitHub action to show stats using this nice tool. However, for some reason does the `config.output=json` query parameter no longer work.

I want to use it, to see all used options/settings, but for unknown reasons does it not return a JSON output for me.
I tried it with my actual link that would have all the used settings and plugins, but also with just https://metrics.lecoq.io/Andre601?config.output=json and neither does return a raw JSON but instead the SVG file itself, which is not what I want.

Can I fix this in some way?

**Comment by Andre601** [comment]
I managed to get a JSON output using the option in the GitHub Action, but now I am wondering, if I setup everything correctly for the action to properly push changes and update the markdown file as I want it to.

If you don't mind would I appreciate, if you could take a quick look at this PR and tell me if everything is correct or needs some changes:
https://github.com/Andre601/Andre601/pull/12

**Comment by lowlighter** [comment, marked as answer]
Hello!

The web instance has a "cache system" which applies for each user, ignoring any further configuration changes (for one hour iirc).
If you retry later you should be able to access the JSON output 👍 

As for https://github.com/Andre601/Andre601/pull/12, you can simplify your workflow by dropping all plugins option (the plugin toggles are still required though)
```yaml
- uses: lowlighter/metrics@latest
      with:
        token: ${{ secrets.METRICS_TOKEN }}
        user: Andre601
        template: markdown
        base: activity, community, repositories, metadata
        config_timezone: Europe/Zurich
        plugin_discussions: yes
        plugin_followup: yes
        plugin_isocalendar: yes
        plugin_languages: yes
        plugin_people: yes
        plugin_stars: yes
```

The `plugin_` prefix is optional when using `embed` function:
```
{%- await embed(`stats-languages`, {languages: true, languages_analysis_timeout: 15, languages_categories:"markup, programming", languages_colors:"github", languages_details:"percentage", languages_ignored:"shell, hack", languages_limit: 8, languages_recent_categories:"markup, programming", languages_recent_days: 14, languages_recent_load: 300, languages_sections:"most-used", languages_threshold:"0%"}) %}
```

You also need to use `{%-` rather than `{%`, since it's actually [EJS syntax](https://github.com/mde/ejs) (you can also use `<%-` instead)

Hope this helps 👍
