### DISCUSSION TITLE
At what interval of time are the stats updated?

### DISCUSSION THREAD

**Discussion by ghost** [lowlighter/metrics#782] [Q&A] [answered]
I was wondering at what interval of time the stats were updated? Also, at the bottom it says "last updated....." what timezone is that in?

**Comment by lowlighter** [comment, marked as answer]
Hi 👋 !

If you're using the GitHub Action, then it depends on which schedule you used (see [Setup GitHub Action workflow](https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md#3%EF%B8%8F-setup-github-action-workflow)). You can change the cron to whatever you'd like, but tbh anything lower than 1 hour is probably overkill
```yml
# Schedule daily updates
on:
  schedule: [{cron: "0 0 * * *"}]
```

For timezone, you need to use `config_timezone` (see [Configure used timezone](https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#-configure-used-timezone)):
```yml
- uses: lowlighter/metrics@latest
  with:
    config_timezone: Europe/Paris
```

The shared web instance (metrics.lecoq.io) has a cache of about one hour, and stats are updated only when it expires and a new request is sent to it
