### DISCUSSION TITLE
Importable configs

### DISCUSSION THREAD

**Discussion by spenserblack** [lowlighter/metrics#794] [Ideas]
Just an idea that popped into my head. It might be overkill, but I wanted to get your opinion on it.

What do you think about being able import configs from another file? For example, something like this:
```yml
uses: lowlighter/metrics@<commit-ish>
with:
  # Some options, like these, should probably never be imported
  token: ${{ secrets.METRICS_TOKEN }}
  committer_token: ${{ github.token }}
  # import config
  config: example.com/path/to/raw/text.yml # or a filepath if the file is available in the workflow runner
  # override some options that may have been set in config
  plugin_foo: no
```

I can think of a few use cases:
1. Splitting up the workflow into multiple files. This can be useful as the [large number of available inputs](https://github.com/lowlighter/metrics/blob/bba5cc491250c48e48b7a6938e9396c67863c8b4/action.yml#L10-L1305) for metrics can make a single step in the workflow quite long.
2. This repo can host some template configs. For example, an `indepth-config.yml` that opts into indepth mode for all available plugins (but user still has to enable the plugins themselves).
3. (This is probably the more fun use case) Sharing configs with other users. Users who are proud of the results of their configurations can show them off and share them, and other users can easily use those configs.
