### DISCUSSION TITLE
Introducing configuration presets!

### DISCUSSION THREAD

**Discussion by lowlighter** [lowlighter/metrics#828] [Announcements]
With 3.19 (currently available on `@master`/`@main` branch), [`config_presets`](https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#-using-presets) option will let you share configurations with other people and/or reuse same settings across different repositories and workflows through YAML presets. 

No need anymore to configure all 200+ options manually, almost any default value of options supported by *metrics* can be overriden through this feature. 

*Example: a simple preset that enable [`📅 isocalendar`](https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md) set it to `full-year` by default*
```yml
schema: v1
with:
  plugin_isocalendar: yes
  plugin_isocalendar_duration: full-year
```

*Example: using a preset in a workflow*
```yml
- uses: lowlighter/metrics@latest
  with:
    config_presets: https://raw.githubusercontent.com/user/repo/main/preset.yml
    # plugin_isocalendar: yes
    # plugin_isocalendar_duration: full-year
```

For convenience, presets published on the [`@presets`](https://github.com/lowlighter/metrics/tree/presets) branch can be included using their identifier prefixed by an `@`:
```yml
- uses: lowlighter/metrics@latest
  with:
    config_presets: "@lunar-red, @ocean-blue"
```

If you have some interesting presets and/or themes you would like to share, feel free to open a pull request on [`@presets`](https://github.com/lowlighter/metrics/tree/presets) branch 👍 ! 

*This feature is based on @spenserblack's idea from #794*
