### DISCUSSION TITLE
Option to add octicons SVGs in Contributors

### DISCUSSION THREAD

**Discussion by Andre601** [lowlighter/metrics#837] [Ideas]
If doable, should there be a way to add and use GitHub's Octicons in the Contributor plugin's `categories` option.

To keep it simple could the syntax follow the basic `:emoji:` one, but perhaps with an `octicons-` prefix and a `12`, `16` or `24` suffix to choose the size variant.

Example workflow:
```yaml
- uses: lowlighter/metrics@latest
  with:
    plugin_contributors: yes
    plugin_contributors_sections: categories
    plugin_contributors_categories: |
      {
        ":octicons-book-16: Documentation": ["README.md", "docs/**"],
        ":octicons-code-16: Code": ["source/**", "src/**"],
        ":octicons-key-asterisk-16: Other": ["*"]
      }
```
The above example would now print an image, but instead of emojis would it use the [book](https://primer.style/octicons/book-16), [code](https://primer.style/octicons/code-16) and [key-asterisk](https://primer.style/octicons/key-asterisk-16) SVGs from Octicons.

It would help keep a sort of consistent GitHub theme in your readme, as emojis (Especially raw ones) can clash with other sections of metrics.
