### DISCUSSION TITLE
fix(app/web): misplaced tabs menu - changes not reflected

### DISCUSSION THREAD

**Discussion by DalpatRathore** [lowlighter/metrics#913] [Q&A] [answered]
Hi! @lowlighter, the code for fixing the misplaced tabs menu is merged but it is not yet reflected on the website. I think the newly merged code, which fixes the misplaced menu tab is not pushed or compiled to the hosting platform and therefore not reflected on the website.

- Try this code in browser devtool
  ```CSS
      .ui.top {
       border-bottom: 1px solid var(--color-border-secondary);
       max-width: 1250px;
       margin: 0 auto;
        }
  ```
- Website will reflect like in the screenshot
  ![Capture](https://user-images.githubusercontent.com/69510006/155367189-3e94eae2-9797-4fae-8661-78d0fac61ec9.JPG)
