### DISCUSSION TITLE
Start list language

### DISCUSSION THREAD

**Discussion by JohnyP36** [lowlighter/metrics#941] [Q&A] [answered]
I followed [the setup to display the language of my Star lists](https://github.com/lowlighter/metrics/blob/master/source/plugins/starlists/README.md)

I made the following code 
```
      - uses: lowlighter/metrics@latest
        with: 
          filename: .github/src/metrics.plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_shuffle_repositories: yes
          plugin_starlists_limit_languages: disable
          plugin_starlists_limit: 2
          plugin_starlists_limit_repositories: 2
```
But the output is `0 Star lists`. See [here](https://github.com/JohnyP36/JohnyP36/blob/main/.github/src/metrics.plugin.starlists.languages.svg)

What did I do wrong? 

Or don't I understand the term `Star lists`? 
*For me `Star lists` are show in the tab `Your Stars` of your profile. For me that's: https://github.com/JohnyP36?tab=stars*
