### ISSUE TITLE
feat(app/metrics): grouped users metrics support

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#1062]
### Discussed in https://github.com/lowlighter/metrics/discussions/1056

Change typing of `user`/`token` to allow multiple values:
```yml
user: foo, bar
token: |
  {
    "foo": ${{ secrets.FOO_TOKEN }},
    "bar": ${{ secrets.BAR_TOKEN }}
  }
```

For action:
- Try to test out multiple user data fetching and use adequate merging strategy (probably best to test with a subset of plugins first).
- Instantiate and use octokit with correct token to fetch out private data if asked by user.

For web instances:
- Make a "round-robin" balancing over tokens to support more than 5000 requests
