### ISSUE TITLE
Inaccurate results regarding certain metrics (notably, commit count)

### ISSUE THREAD

**Issue by ooojustin** [lowlighter/metrics#1629]
I'm using this tool for the first time and getting some inaccurate results.
I couldn't find a good answer elsewhere, so I decided to ask here.

The workflow file I am using is as follows:
<details><summary>Workflow File</summary>
<p>

```yaml
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ooojustin
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
``` 

</p>
</details>

Somehow, I end up with the following result:

![bOXoSJSFJ2.png](https://f002.backblazeb2.com/file/justinooo-upload/07-2024/bOXoSJSFJ2.png)

There are 2 metrics that stand out as extremely off:
1.) Commit count (not sure why)
2.) Pull requests opened/reviewed (likely because I'm no longer part of the org that work was done at)

So I understand the PRs, but I am a bit confused where the commit count number is coming from.
I should note my token has the following scopes: `gist, read:org, read:project, read:user, repo, user:email`
Any info would be appreciated.

_Originally posted by @ooojustin in https://github.com/lowlighter/metrics/discussions/1628_
