### ISSUE TITLE
PageSpeed Insight throws Unexpected error in github actions

### ISSUE THREAD

**Issue by islamzaoui** [lowlighter/metrics#1653]
### Discussed in https://github.com/lowlighter/metrics/discussions/1652

<div type='discussions-op-text'>

<sup>Originally posted by **IslamZaoui** September 21, 2024</sup>
Hello, I facing this Unexpected error when github action generates metrics svg for my portfolio 

```
metrics/compute/IslamZaoui/plugins > pagespeed > completed (error)
  {
    name: 'pagespeed',
    result: {
      error: {
        message: 'Unexpected error',
        instance: TypeError: Cannot destructure property 'score' of 'request.data.lighthouseResult.categories[category]' as it is undefined.
            at Object.default [as pagespeed] (file:///metrics/source/plugins/pagespeed/index.mjs:35:14)
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
            at async file:///metrics/source/plugins/core/index.mjs:67:30
            at async Promise.all (index 0)
            at async metrics (file:///metrics/source/app/metrics/index.mjs:81:22)
            at async retry.retries.retries (file:///metrics/source/app/action/index.mjs:407:40)
            at async retry (file:///metrics/source/app/action/index.mjs:57:22)
            at async file:///metrics/source/app/action/index.mjs:406:28
      }
    }
  }
```

this my metrics.yaml file:
```yaml
# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each month)
  schedule: [{ cron: '0 1 1 * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: IslamZaoui
          template: classic
          base: ''
          config_timezone: Etc/GMT-1
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
          plugin_pagespeed_url: https://islamzaoui.top/en
          debug: yes
```

any suggestion?</div>
