### ISSUE TITLE
Reactions plugin doesn't count reactions from PR comments

### ISSUE THREAD

**Issue by spenserblack** [lowlighter/metrics#333]
## To Reproduce
```yaml
  # ...
  steps:
  - uses: lowlighter/metrics@v3.9
    with:
      # ...
      plugin_reactions: yes
      plugin_reactions_details: percentage
```

## Actual Behavior

It seems that the reactions plugin is not counting reactions from pull request comments. I have a :heart: reaction to https://github.com/lowlighter/metrics/pull/325#issuecomment-848190728, but it doesn't seem to be included in [my metrics](https://github.com/spenserblack/spenserblack/blob/65cc55509e72df543bda9cd7f9366cd2b96f733e/metrics.svg) (:heart: is still 0%).

## Expected Behavior

Reactions from pull request comments being included.

## Other Comments

- I think this issue invalidates my concerns in #255 :sweat_smile: 
- I wasn't completely sure if this was a bug or a feature request. But, since ignoring dependabot comments per #255 seemed like a concern at the time, I assumed that counting PR comment reactions was expected behavior.
