### ISSUE TITLE
wakatime: Error when `projects`/`languages`/`editors`/`operating_systems` is `null`

### ISSUE THREAD

**Issue by cherryblossom000** [lowlighter/metrics#391]
[Relevant config](https://github.com/cherryblossom000/cherryblossom000/blob/main/.github/workflows/metrics.yml):

```yml
name: metrics
# ...
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        # ...
        plugin_wakatime: true
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
        plugin_wakatime_sections: time, languages, languages-graphs, editors, os
        plugin_wakatime_url: https://wakapi.dev
        plugin_wakatime_user: cherryblossom # using default of current doesn't work
```

[Error](https://github.com/cherryblossom000/cherryblossom000/runs/2838256728?check_suite_focus=true#step:2:427):

```
metrics/compute/cherryblossom000 > 1 errors !
[
  {
    name: 'wakatime',
    result: {
      error: {
        message: 'An error occured',
        instance: TypeError: Cannot read property 'map' of null
            at Object.default [as wakatime] (file:///metrics/source/plugins/wakatime/index.mjs:30:31)
            at processTicksAndRejections (node:internal/process/task_queues:94:5)
            at async file:///metrics/source/plugins/core/index.mjs:46:30
            at async Promise.all (index 12)
            at async metrics (file:///metrics/source/app/metrics/index.mjs:61:22)
            at async file:///metrics/source/app/action/index.mjs:290:24
      }
    }
  }
]
```

I'm not sure about Wakatime, but [Wakapi](https://wakapi.dev/) allows you to hide your projects, languages, editors, and OSes from the API:

![Screenshot of Wakapi ‘Public Data’ settings, showing that you can toggle ‘Share projects’, ‘Share languages’, ‘Share editors’, ‘Share operating systems’, ‘Share machines’, and ‘Share project labels’ for the endpoint `/api/v1/users/{user}/stats/{range}`.](https://user-images.githubusercontent.com/31467609/122205608-cbfa2b00-cee3-11eb-9e98-387dbc367f9b.png)

The error occurs here:

https://github.com/lowlighter/metrics/blob/8b4bf0c8c425bef12134f7ab39ef6ccf50dbc3e9/source/plugins/wakatime/index.mjs#L30

because `stats.projects` is null.
