### ISSUE TITLE
Classic template shows when it is not supposed to?

### ISSUE THREAD

**Issue by TheQuackyDuck** [lowlighter/metrics#412]
In my `main.yml`, I have the following:

```
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: lowlighter/metrics 😁
        uses: lowlighter/metrics@latest
        with:
          user: TheQuackyDuck
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_activity_limit: 5                                 
          plugin_activity_days: 365 # lol                                      # haha                      e
          plugin_activity_filter: issue, pr, ref/create, ref/delete, release, review, comment, wiki, fork, public, member
          plugin_languages: yes
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." 
          plugin_languages_details: bytes-size, percentage              
          plugin_la nguages_threshold: 2%                             
          plugin_languages_limit: 20
          plugin_languages_indepth: no                                  
          plugin_languages_recent_load: 500                             
          plugin_languages_recent_days: 7
          plugin_followup: yes
          plugin_followup_sections: repositories, user
```

It doesn't have the classic template thing. But as you can see on my profile, it shows the thing it supposed to show when I put `template: classic`.

Am I doing something wrong or is this a problem with the metrics?
