### ISSUE TITLE
The metrics.svg file is not getting created

### ISSUE THREAD

**Issue by shnkreddy98** [lowlighter/metrics#42]
I followed the steps as you specified in the repos readme.md. After I create the GitHub action workflow you said it will generate a new metrics image, but there are no images created.

**Comment by lowlighter** [comment]
Hello !

Since you're using `main` instead of `master`, you need to change it in your [workflow](https://github.com/shnkreddy98/shnkreddy98/blob/main/.github/workflows/main.yml#L5).

Scheduled runs are working (each hour), but it seems you forgotten to put your personal token in your repository secrets (`${{ secrets.METRICS_TOKEN }}` appears to be empty)

After fixing these, it should work 👍

**Comment by shnkreddy98** [comment]
After changing the master to main it worked, but the token issue is still there, I have added the token inside the secret section of the repository, but should i replace some part of ${{ secrets.METRICS_TOKEN }} with the token key also

**Comment by lowlighter** [comment]
Yes, since you named your secret `MY_METRICS` you should use `${{ secrets.MY_METRICS }}` instead

**Comment by shnkreddy98** [comment]
Alright, Thank you ..

Good work.... Keep it up

**Comment by lowlighter** [comment]
Thank you !

**Comment by shnkreddy98** [comment]
So I tried to add your workflow and i get this error
```
Error: An error occured during rendering, dying
Error: Process completed with exit code 1.
```
do you know why?

i changed all the secret tokens to MY_METRICS and the branch to main

**Comment by lowlighter** [comment]
My workflow is configured to die in case of error so that's why.
The `music` plugin requires additional setup so it won't work, and the third step use a bot account (`${{ secrets.METRICS_BOT_TOKEN }}`) instead because `project` plugin requires additional scopes.

If you use the following in your workflow, it should works :
```yaml
name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "main"
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.MY_METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          # plugin_music: yes
          # plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          # plugin_music_limit: 2
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          # plugin_languages_skipped: lowlighter
          # plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          
      - name: Personal metrics (additional)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.MY_METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "metadata"
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3

      # - name: Personal projects
      # uses: lowlighter/metrics@latest
      # with:
      #   filename: metrics.projects.svg
      #   token: ${{ secrets.METRICS_BOT_TOKEN }}
      #   committer_token: ${{ secrets.GITHUB_TOKEN }}
      #   user: lowlighter
      #   base: ""
      #   plugin_projects: yes
      #   plugin_projects_repositories: lowlighter/metrics/projects/1
      #   plugin_projects_limit: 0
      #   config_timezone: Europe/Paris

```
