### ISSUE TITLE
Pagespeed Plugin: Wrong website domain shown in image, when using plugin_pagespeed_url

### ISSUE THREAD

**Issue by JonathanTreffler** [lowlighter/metrics#43]
**Bug description**
If you use the plugin_pagespeed_url override the domain under the "pagespeed insights" text is still the users profile website.

**Expected behavior**
It should show the plugin_pagespeed_url domain.

**To Reproduce**
Generate image with plugin_pagespeed_url.

**Additional context and screenshots**
I want to use this as a badge for a repository, wich deploys a github pages website, not for my personal profile repository.
So i need the correct domain there, to not confuse anyone.

```
- uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}

          # Options
          template: classic
          filename: pagespeed.svg
          base: ""
          config_timezone: Europe/Berlin
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://example.com/
````

generates this:

![image](https://user-images.githubusercontent.com/28999431/104061730-6f3e6a00-51f9-11eb-9bc8-23962f0f7ff3.png)

It should show "example.com" and not "jonathan-treffler.de"

**Comment by lowlighter** [comment]
Hello, 

Thanks for reporting this issue, it's actually a nice catch !

It is patched on `@master` branch right now so you can change your workflow with the following instead (using the prebuilt image to save some time) :
```yaml
- uses: lowlighter/metrics@master
  with:
    use_prebuilt_image: master
```

If you're not in hurry, you can wait for `@latest` to be updated to v3.2, but I'm not sure when it'll be out since I'm working on a new plugin and I have to patch the web instance to make it work on Safari.

It's actually a good use case, I think I'll add support for pagespeed plugin for the repository template to make it easier.
