### ISSUE TITLE
Did you forget to run actions/checkout before running your local action?

### ISSUE THREAD

**Issue by AnuragAnalog** [lowlighter/metrics#449]
### Discussed in https://github.com/lowlighter/metrics/discussions/448

<div type='discussions-op-text'>

<sup>Originally posted by **AnuragAnalog** August  4, 2021</sup>
I am getting the following error when I am trying to set up the metrics in my readme file.

Error is: **Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/AnuragAnalog/AnuragAnalog/main'. Did you forget to run actions/checkout before running your local action?**

I have a main branch in my repository and the code in the action.yml file is

```yaml
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: AnuragAnalog/AnuragAnalog@main
      # If you make changes on your fork, be sure not leave @latest as tag!
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
```

My Username is: AnuragAnalog
Repo name is: AnuragAnalog
The branch name is: main</div>
