### ISSUE TITLE
How does project plug-in display projects that are not in the repositories

### ISSUE THREAD

**Issue by Ormissia** [lowlighter/metrics#46]
I want to use the project plug-in to display projects that are not in the respostories, but I don't know how to write ":repository" after plugin_projects_repositories. Because those projects are not in any repositories.

**Comment by lowlighter** [comment]
Hello !

If you mean to display projects that are on your profile like these :
![image](https://user-images.githubusercontent.com/22963968/104126092-08d15d00-535b-11eb-8c60-439723697013.jpeg)

This should do it :
```yaml
- uses: lowlighter/metrics@latest
   with:
     # other options
     plugin_projects: yes
     plugin_projects_limit: 2
```

As you can see, no need to use `plugin_projects_repositories`, it actually looks for you personal projects first 🙂

**Comment by Ormissia** [comment]
After I changed workflows , it worked correctly.
```yml
- uses: lowlighter/metrics@latest
   with:
     # other options
     plugin_projects: yes
     plugin_projects_limit: 2
```
Thank you very much for your reply
