### ISSUE TITLE
got error when update notable contribution

### ISSUE THREAD

**Issue by slowy07** [lowlighter/metrics#491]
hello!, sorry, i wanna ask something, i'm have several warnings when action was running and success, but display svg got error on notable contribution this my configuration action code

```yml
name: Metrics
on:
  # Schedule updates (each hour)
  
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: display_information_1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.MATRICS }}
          user: slowy07
          # template
          template: classic
          # base
          base: activity, community, repositories, metadata
          # timezone
          config_timezone: Asia/Jakarta
          # filename
          filename: github-metrics.svg
          # programming language
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: my-testing-repo
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%
          plugin_languages_limit: 15
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: no
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 7
          commits_authoring: arfy slowy
          # coding habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          # line of code changed
          plugin_lines: yes
          # topics
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          # recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          # notable contrib
          plugin_notable: yes
          plugin_notable_filter: stars:>500
          plugin_notable_repositories: no

      #achievements
      - name: display_achievement
        uses: lowlighter/metrics@latest
        with:
          filename: achievements-metrics.svg
          token: ${{ secrets.MATRICS }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          config_display: large
```

for secret  token i was typo but works very well. when generate the svg and displaying the notable contributions got message
``an error occured``, may i wrong or just github bugs?
thanks !,happy good day
