### ISSUE TITLE
Error: Process completed with exit code 125 when using metrics@master

### ISSUE THREAD

**Issue by aleen42** [lowlighter/metrics#50]
The following configuration has run wrong with throwing `Error: Process completed with exit code 125.`

```yaml
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token restricted to current repository, which is used to push files in it
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "" # Only show header
          plugin_isocalendar: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14 # Max age for events, set to 0 for unlimited:
```

The detailed stack:

```
Run lowlighter/metrics@master
Environment variable: loaded
Source: lowlighter
Version: 3.2.0-beta
Image tag: v3.2
Is released version: 0
Using released version v3.2, will pull docker image from GitHub registry
Image name: ghcr.io/lowlighter/metrics:v3.2
Unable to find image 'ghcr.io/lowlighter/metrics:v3.2' locally
docker: Error response from daemon: name unknown.
See 'docker run --help'.
Error: Process completed with exit code 125.
```
