### ISSUE TITLE
`plugin_notable_repositories` option is ignored

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/metrics#672]
### Discussed in https://github.com/lowlighter/metrics/discussions/670

<div type='discussions-op-text'>

<sup>Originally posted by **s-takehana** November 18, 2021</sup>
`plugin_notable_repositories` option is ignored only when `plugin_notable_repositories`  + `plugin_notable_from: all`.

```yaml
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
```

Is this a bug?
</div>
