### ISSUE TITLE
Language colors hard to separate

### ISSUE THREAD

**Issue by b3z** [lowlighter/metrics#70]
Is it possible to change the language colors?

Because I don't know if the big bar is Haskell, C or CSS?

![image](https://user-images.githubusercontent.com/47346598/105467108-84a1a280-5c95-11eb-8b55-8d45b95060ae.png)

See here: https://github.com/b3z

**Comment by lowlighter** [comment]
Hello !

Languages legend is ordered the same way as bars (from left to right), so it's Haskell.

Currently metrics use the same language color used by GitHub, but I confess in your case it's a bit hard to distinguish.

I'll add an option to use custom colors so it's possible to handle these cases 👍

**Comment by lowlighter** [comment]
Added `plugin_languages_colors` in #72 

Basically you can either pass an index (0 to 7) or a language name (case insensitive) with a color (hex or named) to override GitHub's default colors. You can override multiple values with comma :
```yaml
plugin_languages_colors: "css:red"             # Make css red
plugin_languages_colors: "css:#ff0000"         # Make css red (hex version)
plugin_languages_colors: "0:red"               # Make language 0 (first one) red
plugin_languages_colors: "rainbow"             # Predefined set of easily distinguishable colors 
plugin_languages_colors: "0:blue, css:#ff0000" # Make most used language blue and css red 
```

It's not the most practical way, but GitHub Action does not supports dictionnaries as input afaik, and stringified JSON seemed overkill (and not practical for web instance).

It's already available on `@master` branch and will be on `@latest` on next release.
