### ISSUE TITLE
Action exceeding the maximum execution time of 360 minutes

### ISSUE THREAD

**Issue by matievisthekat** [lowlighter/metrics#731]
This has been happening only for the last couple of hours.

The job fails with the error `The job running on runner GitHub Actions 3 has exceeded the maximum execution time of 360 minutes.`
Further investigation shows that the job was in fact running for 6 hours.

<details>
	<summary>Copy of action log</summary>

```
────────────────────────────────────────────────────────────────────────────────────────
Metrics                                                  │  
(node:11) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Setup                                                    │ complete
Version                                                  │ 3.17.0-beta
Using prebuilt image                                     │ true
Debug mode                                               │ false
Debug flags                                              │ (none)
GitHub token                                             │ (provided)
Github GraphQL API                                       │ ok
Github REST API                                          │ ok
Token validity                                           │ seems ok
GitHub account                                           │ matievisthekat
Current repository                                       │ matievisthekat/matievisthekat
Committer token                                          │ (provided)
Committer branch                                         │ master
Committer head branch                                    │ master
Committer REST API                                       │ ok
Committer account                                        │ (github-actions)
Committer head branch status                             │ ok
Previous render sha                                      │ d977b5ffc80dc570c06aee01718fb1cb7bb6166d
SVG output                                               │ recent-metrics.svg
SVG optimization                                         │ css, xml
SVG verification after generation                        │ false
────────────────────────────────────────────────────────────────────────────────────────
Templates                                                │  
Community templates                                      │ (none)
Template used                                            │ classic
Query additional params                                  │ {}
────────────────────────────────────────────────────────────────────────────────────────
Core                                                     │  
Rendered markdown output path                            │ TEMPLATE.md
Extra CSS                                                │ 
Timezone used                                            │ Africa/Johannesburg
Configure content order                                  │ (none)
Use twemojis instead of emojis                           │ false
Use GitHub custom emojis                                 │ true
Render display width                                     │ regular
SVG CSS animations                                       │ true
Encode images links into base64 data                     │ true
Image padding                                            │ 0, 0
Output image format                                      │ auto
Experimental features                                    │ (none)
Plugin errors                                            │ (displayed in generated image)
────────────────────────────────────────────────────────────────────────────────────────
Base content                                             │  
Number of repositories to use                            │ 100
Number of repositories to load at once by queries        │ 100
Include forks in metrics                                 │ false
Repositories affiliations                                │ owner
Default repositories to skip                             │ (none)
List of surnames or email addresses you use when authoring commits │ .user.login
Base sections                                            │ (none)
────────────────────────────────────────────────────────────────────────────────────────
Coding habits                                            │  
Number of events to use                                  │ 1000
Maximum event age                                        │ 30
Display coding habits collected facts based on recent activity │ false
Display coding habits charts based on recent activity    │ true
Trim unused hours on daily chart                         │ false
────────────────────────────────────────────────────────────────────────────────────────
Music plugin                                             │  
Music provider                                           │ spotify
Music provider personal token                            │ (provided)
Plugin mode                                              │ recent
Embed playlist url                                       │ 
Maximum number of tracks to display                      │ 5
Display when the track was played                        │ true
Time period for top mode                                 │ short
Whether to show tracks or artists in top mode            │ tracks
Music provider username                                  │ .user.login
────────────────────────────────────────────────────────────────────────────────────────
Recently starred repositories                            │  
Maximum number of stars to display                       │ 4
────────────────────────────────────────────────────────────────────────────────────────
WakaTime plugin                                          │  
WakaTime API token                                       │ (provided)
WakaTime time range                                      │ 7
Sections to display                                      │ time, projects, editors, os
Maximum number of entries to display per graph           │ 5
Address where to reach your Wakatime instance            │ wakatime.com
Your Wakatime user on the selfhosted Wakapi instance     │ current
────────────────────────────────────────────────────────────────────────────────────────
Rendering                                                │  
Error: The operation was canceled.
```

</details>

and here is a copy of my workflow config

*[view file](https://github.com/matievisthekat/matievisthekat/blob/master/.github/workflows/recent-metrics.yml)*
```yaml
name: Recent Metrics
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 * * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: Africa/Johannesburg
          config_padding: 0, 0
          filename: recent-metrics.svg
          
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: no
          plugin_habits_charts: yes
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, editors, os
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 5
          plugin_music_played_at: yes
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
```

The action seems to be running for 6 hours. Is it maybe getting stuck in some kind of infinite loop? A number of the runs for this workflow have had this error. I will link to them below:

(From oldest to newest)
- https://github.com/matievisthekat/matievisthekat/actions/runs/1625653947
- https://github.com/matievisthekat/matievisthekat/actions/runs/1625780978
- https://github.com/matievisthekat/matievisthekat/actions/runs/1625895305
- (then three successful runs)
- https://github.com/matievisthekat/matievisthekat/actions/runs/1626454912 (this one ran for 3 hours before I cancelled it)
- (then one successful run)
- https://github.com/matievisthekat/matievisthekat/actions/runs/1626769078 (this one ran for 37 minutes before I cancelled it)

**Comment by bossm0n5t3r** [comment]
same here

**Comment by icy-blue** [comment]
I got failure either. The action with metrics@latest will cause this problem.
When I tried to switch the version to v3.16, the action continues running for more than 10 min (2-3 min before, for reference, I will follow the progress and update later).
Some runs reported failure within less than 6 hrs, which action workflow file is not changed.
The log of the run mentioned is [here](https://github.com/icy-blue/icy-blue/runs/4639603566). Is the renderer okay for running?
<details>
<summary>Here is a copy of my workflow config</summary>

```
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: icy-blue
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_setup: npm ci       # Command to setup target repository
          plugin_licenses_ratio: yes          # Display used licenses ratio
          plugin_licenses_legal: yes          # Display permissions, limitations and conditions
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_people: yes
          plugin_people_limit: 100
```
</details>
